services:

#   appsmith:
#     image: index.docker.io/appsmith/appsmith-ce
#     container_name: appsmith
#     ports:
#         - "8080:80"
#         - "4431:443"
#     volumes:
#         - ./appsmith_storage:/appsmith-stacks
#     restart: unless-stopped

   selenium_chrome:
     image: selenium/standalone-chrome:latest
     container_name: selenium_chrome
     ports:
       - "4444:4444"
       - "7900:7900"
     shm_size: "2g"

