name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - name: Clean up workspace before checkout
        run: |
          echo "Workspace is at: ${{ github.workspace }}"
          rm -rf "${{ github.workspace }}/*" # /home/runner/work/selenium_appsmith/*
          sudo chmod -R 777 "${{ github.workspace }}"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Unzip Appsmith's test data volume
        run: |
          unzip -q selenium_appsmith/tests/appsmith_test_data.zip -d selenium_appsmith/tests/appsmith_test_data
          echo -e "$(pwd)"
          ls -la selenium_appsmith/tests/appsmith_test_data  # Verify contents
          sudo chmod -R 777 selenium_appsmith/tests/appsmith_test_data
          sudo chown -R root:root selenium_appsmith/tests/appsmith_test_data

      - name: Create docker network
        run: |
          docker network create appsmith-network

      - name: Run Appsmith container
        run: |
          docker run --name appsmith --network appsmith-network -d -v "${{ github.workspace }}/selenium_appsmith/tests/appsmith_test_data:/appsmith-stacks" -p 8080:80 -p 4431:443 --shm-size=2g index.docker.io/appsmith/appsmith-ce:v1.64

      - name: Run Selenium container
        run: |
          docker run --name selenium_chrome --network appsmith-network -d -p 4444:4444 -p 7900:7900 --shm-size=2g selenium/standalone-chrome:134.0

      - name: Run polling script
        run: |
          chmod +x ./poll_services.sh
          ./poll_services.sh

      - name: Run Tests
        run: pytest selenium_appsmith/tests/test_with_selenium.py
