name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: print location
        run: echo -e "$(pwd) \n$(ls -l)"

      - name: Run Tests
        run: pytest selenium_appsmith/tests/test_github_aciton.py
        working-directory: ./selenium_appsmith
