name: Python Tests

on: [push, pull_request]

jobs:
  test-appsmith-with-selenium:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - name: Clean up workspace before checkout
        run: |
          echo "Workspace is at: ${{ github.workspace }}"
          rm -rf "${{ github.workspace }}/*" # /home/runner/work/selenium_appsmith/*
          sudo chmod -R 777 "${{ github.workspace }}"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Unzip Appsmith's test data volume
        run: |
          unzip -q selenium_appsmith/tests/appsmith_test_data.zip -d selenium_appsmith/tests/appsmith_test_data
          echo -e "$(pwd)"
          ls -la selenium_appsmith/tests/appsmith_test_data  # Verify contents
          sudo chmod -R 777 selenium_appsmith/tests/appsmith_test_data
          sudo chown -R root:root selenium_appsmith/tests/appsmith_test_data

      - name: Set up Docker Compose
        run: |
          docker compose up -d
          sleep 2
          docker ps

      - name: Run polling script
        run: |
          chmod +x ./.github/workflows/poll_services.sh
          ./.github/workflows/poll_services.sh

      - name: Run Tests
        run: pytest selenium_appsmith/tests/test_with_selenium.py
