name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Clean up workspace before checkout
        run: |
          echo "Workspace is at: ${{ github.workspace }}"
          rm -rf "${{ github.workspace }}/*" # /home/runner/work/selenium_appsmith/*
          sudo chmod -R 777 "${{ github.workspace }}"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Unzip Appsmith's test data volume
        run: |
          unzip -q selenium_appsmith/tests/appsmith_test_data.zip -d selenium_appsmith/tests/appsmith_test_data
          ls -la selenium_appsmith/tests/appsmith_test_data  # Verify contents
          echo -e "$(pwd)"
          #CURRENT_USER=$(stat -c '%u' docker-compose.yml)
          #CURRENT_USER=$(stat -c '%g' docker-compose.yml)
          sudo chmod -R 777 selenium_appsmith/tests/appsmith_test_data

      - name: Run Appsmith container
        run: |
          docker run --name appsmith -v "${{ github.workspace }}/selenium_appsmith/tests/appsmith_test_data:/appsmith-stacks" -p 8080:80 -p 4431:443 --shm-size=2g index.docker.io/appsmith/appsmith-ce:v1.65

      - name: Run Selenium container
        run: |
          docker run --name selenium_chrome -p 4444:4444 -p 7900:7900 --shm-size=2g selenium/standalone-chrome:134.0

      - name: Run Tests
        run: pytest selenium_appsmith/
